import TextInput from "components/TextInput";
import Head from "next/head";
import Header from "components/Header";
import Results from "components/Results";
import { useEffect, useState } from "react";
import axios from "axios";

export default function Home() {
  const [url, setUrl] = useState("");
  const [error, setError] = useState(undefined);
  const [res, setRes] = useState(undefined);

  const handleSubmit = (e) => {
    e.preventDefault();
    if (url === "") return setError("Enter your website url");
    if (!url?.startsWith("http")) return setError("Enter a valid Url");

    axios
      .get(url)
      .then((res) => {
        // get config
        // headers
        // status
        console.log(res);
        setRes(res)
      })
      .catch((error) => {
        console.log(error);
      });
  };

  useEffect(() => {
    setTimeout(() => {
      setError(undefined);
    }, 5000);
  }, [error]);

  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      <header
        className="flex justify-center items-center"
        style={{ height: "400px" }}
      >
        <div className="w-1/2 mx-auto">
          <TextInput
            error={error}
            handleSubmit={handleSubmit}
            onChange={(e) => setUrl(e.target.value)}
            url={url}
          />
        </div>
      </header>

      <main className="borde" style={{ height: "500px" }}>
        <Results data={res} />
      </main>
    </div>
  );
}
